### ISSUE TITLE
Data is not encrypted

### ISSUE THREAD

**Issue by anandhkumares** [tusharhero/bincode#7]
If some one like to share data using bincode it should be encrypted.

**Comment by tusharhero** [comment]
what do you mean? Should I add a password requirement?

**Comment by anandhkumares** [comment]
like you could use some ecryption methods.

**Comment by tusharhero** [comment]
what exactly does encryption mean?

**Comment by anandhkumares** [comment]
https://en.wikipedia.org/wiki/Encryption

**Comment by anandhkumares** [comment]
easiest method and easiest things to crack https://en.wikipedia.org/wiki/Caesar_cipher

**Comment by tusharhero** [comment]
@anandh-kumar isnt the whole point of this that people could easily scan it. If I encrypt it wouldn't people have to type a password to decrypt it?

**Comment by tusharhero** [comment]
> easiest method and easiest things to crack https://en.wikipedia.org/wiki/Caesar_cipher

what would be the benefit of adding that?

**Comment by anandhkumares** [comment]
Yes, but it wont be turned on by default people can use it if they need.

**Comment by anandhkumares** [comment]
> > easiest method and easiest things to crack https://en.wikipedia.org/wiki/Caesar_cipher
> 
> what would be the benefit of adding that?

No use. an example for you.

**Comment by tusharhero** [comment]
That doesnt sound like a bincode problem. If someone wanted that, they could implement it using their own code and use `bincode.py` to generate bincodes.

**Comment by anandhkumares** [comment]
_anandh left the issue_

**Comment by tusharhero** [comment]
Ok I am closing the issue
